name: Regenerate Database
env:
  BRICKSTORE_BUILD_NUMBER: '1208'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3,15 * * *' # run at 2 AM UTC

jobs:
  update:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Set tag name
      run: echo "TAGNAME=$(date +'%Y.%m.%d-%H.%M')" >> $GITHUB_ENV

    - uses: actions/checkout@v3

    - name: "TODO: Cache"
      run: |
        mkdir ./data

    - name: Run BrickStore
      shell: bash
      run: |
        docker run --rm \
               -e BRICKLINK_USERNAME="${{ secrets.BRICKLINK_USERNAME }}" \
               -e BRICKLINK_PASSWORD="${{ secrets.BRICKLINK_PASSWORD }}" \
               -e BRICKLINK_AFFILIATE_APIKEY="${{ secrets.BRICKLINK_AFFILIATE_APIKEY }}" \
               -e REBRICKABLE_APIKEY="${{ secrets.REBRICKABLE_APIKEY }}" \
               -v "./data:/data" \
               --user $(id -u) \
               --name "brickstore-backend" \
               rgriebl/brickstore-backend:${BRICKSTORE_BUILD_NUMBER}

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "data/cache/BrickStore/downloads.zip,data/db/database-v*.lzma"
        commit: main
        tag: ${{ env.TAGNAME }}
